// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEYSrWTX3GOrsz2zbsXcVMPlLTdo0Mhro',
    appId: '1:525189608603:web:e7de5be2cdeb080de3c23e',
    messagingSenderId: '525189608603',
    projectId: 'iegy-bcbff',
    authDomain: 'iegy-bcbff.firebaseapp.com',
    storageBucket: 'iegy-bcbff.appspot.com',
    measurementId: 'G-KXMPDRM6YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAghGSXNbDHdghPIdkOy3pZZM8wL3JnI0',
    appId: '1:525189608603:android:13e7f6e2023ea8f9e3c23e',
    messagingSenderId: '525189608603',
    projectId: 'iegy-bcbff',
    storageBucket: 'iegy-bcbff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0fEl0UrQk1Or8cF2os4GSgJzBaH99SEk',
    appId: '1:525189608603:ios:4c1b392af0cc60a7e3c23e',
    messagingSenderId: '525189608603',
    projectId: 'iegy-bcbff',
    storageBucket: 'iegy-bcbff.appspot.com',
    iosBundleId: 'com.example.iegy',
  );
}
